# product_segmentation_app.py
import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from io import BytesIO
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import colors

# ---------- Helper ----------
def _pct_bins_classifier(pct: float, a_pct: float, b_pct: float) -> str:
    if pct <= a_pct:
        return "A"
    elif pct <= a_pct + b_pct:
        return "B"
    return "C"

def product_segmentation(df: pd.DataFrame, item_col: str, sales_col: str, revenue_col: str,
                         a_pct: float = 70, b_pct: float = 20) -> pd.DataFrame:
    dfp = df[[item_col, sales_col, revenue_col]].copy()
    dfp = dfp.rename(columns={item_col: "Item", sales_col: "SalesQty", revenue_col: "Revenue"})

    dfp["SalesQty"] = pd.to_numeric(dfp["SalesQty"], errors="coerce").fillna(0)
    dfp["Revenue"] = pd.to_numeric(dfp["Revenue"], errors="coerce").fillna(0)

    items = dfp.groupby("Item", as_index=False).agg({"SalesQty": "sum", "Revenue": "sum"})
    items = items.sort_values("SalesQty", ascending=False).reset_index(drop=True)

    total_sales = items["SalesQty"].sum()
    items["CumulPct_Sales"] = np.where(total_sales > 0,
                                       100.0 * items["SalesQty"].cumsum() / total_sales,
                                       0.0)
    items["ABC_Sales"] = items["CumulPct_Sales"].apply(lambda p: _pct_bins_classifier(p, a_pct, b_pct))

    items["CumulPct_Revenue_withinSales"] = 0.0
    items["ABC_Revenue_withinSales"] = "C"
    for grp in ["A", "B", "C"]:
        mask = items["ABC_Sales"] == grp
        sub = items.loc[mask].sort_values("Revenue", ascending=False).copy()
        tot_rev = sub["Revenue"].sum()
        if tot_rev > 0 and len(sub) > 0:
            sub["CumulPct_Revenue_withinSales"] = 100.0 * sub["Revenue"].cumsum() / tot_rev
            sub["ABC_Revenue_withinSales"] = sub["CumulPct_Revenue_withinSales"].apply(
                lambda p: _pct_bins_classifier(p, a_pct, b_pct)
            )
        else:
            sub["CumulPct_Revenue_withinSales"] = 0.0
            sub["ABC_Revenue_withinSales"] = "C"
        items.loc[sub.index, "CumulPct_Revenue_withinSales"] = sub["CumulPct_Revenue_withinSales"]
        items.loc[sub.index, "ABC_Revenue_withinSales"] = sub["ABC_Revenue_withinSales"]

    items["Final_Class"] = items["ABC_Sales"] + "-" + items["ABC_Revenue_withinSales"]
    return items

# ---------- PDF Generator ----------
def create_summary_pdf(result_df, a_pct, b_pct, figs):
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4)
    styles = getSampleStyleSheet()
    story = []

    # Title
    today = datetime.today().strftime("%Y-%m-%d")
    story.append(Paragraph(f"ABC Segmentation Report {today}", styles["Title"]))
    story.append(Paragraph("Generated by Segmentation Toolkit | Confidential", styles["Normal"]))
    story.append(Spacer(1, 12))

    # ---- Sales Summary ----
    total_sales = result_df["SalesQty"].sum()
    sales_split = result_df.groupby("ABC_Sales")["SalesQty"].sum().reindex(["A", "B", "C"]).fillna(0)

    story.append(Paragraph("Sales Summary", styles["Heading2"]))
    sales_table_data = [
        ["Total Sales", f"{int(total_sales):,}", "A Sales", f"{int(sales_split['A']):,}"],
        ["B Sales", f"{int(sales_split['B']):,}", "C Sales", f"{int(sales_split['C']):,}", ""]
    ]
    table1 = Table(sales_table_data, colWidths=[100, 100, 100, 100])
    table1.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.lightblue),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.black),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
    ]))
    story.append(table1)
    story.append(Spacer(1, 12))

    # ---- Revenue Summary ----
    total_revenue = result_df["Revenue"].sum()
    revenue_split = result_df.groupby("Final_Class")["Revenue"].sum().reindex(
        ["A-A","A-B","A-C","B-A","B-B","B-C","C-A","C-B","C-C"]).fillna(0)

    story.append(Paragraph("Revenue Summary", styles["Heading2"]))
    revenue_table_data = [["Total Revenue", f"{int(total_revenue):,}"]]
    # break into rows of 4 subcategories for readability
    row = []
    for i, (cls, val) in enumerate(revenue_split.items(), 1):
        row.extend([cls, f"{int(val):,}"])
        if i % 4 == 0 or i == len(revenue_split):
            revenue_table_data.append(row)
            row = []

    table2 = Table(revenue_table_data, colWidths=[60, 80, 60, 80, 60, 80, 60, 80])
    table2.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.lightblue),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.black),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
    ]))
    story.append(table2)
    story.append(Spacer(1, 12))

    # ---- Inputs ----
    story.append(Paragraph("Inputs Used", styles["Heading2"]))
    inputs_table_data = [
        ["A % Cutoff", f"{a_pct}%", "B % Cutoff", f"{b_pct}%"],
        ["Total Items", str(len(result_df)), "", ""]
    ]
    table3 = Table(inputs_table_data, colWidths=[100, 100, 100, 100])
    table3.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.black),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
    ]))
    story.append(table3)
    story.append(Spacer(1, 12))

    # ---- Graphs ----
    story.append(Paragraph("Graphs", styles["Heading2"]))
    for fig in figs:
        img_buf = BytesIO()
        fig.savefig(img_buf, format="png", bbox_inches="tight", dpi=100)
        img_buf.seek(0)
        story.append(Image(img_buf, width=380, height=220))
        story.append(Spacer(1, 6))

    doc.build(story)
    buffer.seek(0)
    return buffer

# ---------- Streamlit UI ----------
st.set_page_config(page_title="Product Segmentation (ABC Analysis)", page_icon="📦", layout="wide")
st.title("📦 Product Segmentation — ABC Analysis with Subcategories")

uploaded_file = st.file_uploader("Upload Excel file", type=["xlsx"])
if uploaded_file:
    df = pd.read_excel(uploaded_file)
    st.subheader("Preview of Uploaded Data")
    st.dataframe(df.head())

    st.sidebar.header("Parameters")
    item_col = st.sidebar.selectbox("Item Column", df.columns, index=0)
    sales_col = st.sidebar.selectbox("Sales Quantity Column", df.columns, index=1)
    revenue_col = st.sidebar.selectbox("Revenue Column", df.columns, index=2)
    a_pct = st.sidebar.slider("A % cutoff", 10, 90, 70, 1)
    b_pct = st.sidebar.slider("B % cutoff", 5, 40, 20, 1)

    if st.button("Run Product Segmentation"):
        result = product_segmentation(df, item_col, sales_col, revenue_col, a_pct, b_pct)

        st.subheader("Segmentation Result (first 20 rows)")
        st.dataframe(result.head(20))

        # Graphs
        figs = []
        fig1, ax1 = plt.subplots()
        result["Final_Class"].value_counts().plot(kind="bar", ax=ax1)
        ax1.set_title("Distribution of Final Classes")
        st.pyplot(fig1); figs.append(fig1)

        fig2, ax2 = plt.subplots()
        result["Final_Class"].value_counts().plot(kind="pie", autopct="%1.1f%%", ax=ax2)
        ax2.set_ylabel("")
        ax2.set_title("Final Class Distribution")
        st.pyplot(fig2); figs.append(fig2)

        fig3, ax3 = plt.subplots()
        ax3.scatter(result["SalesQty"], result["Revenue"], c=pd.factorize(result["Final_Class"])[0])
        ax3.set_xlabel("SalesQty"); ax3.set_ylabel("Revenue")
        ax3.set_title("Sales vs Revenue by Class")
        st.pyplot(fig3); figs.append(fig3)

        # PDF export
        pdf_buf = create_summary_pdf(result, a_pct, b_pct, figs)
        st.download_button("📑 Download PDF Report (A4)", data=pdf_buf,
                           file_name="ABC_Segmentation_Report.pdf", mime="application/pdf")
